### ISSUE TITLE
TEST: Get tests in passing state

### ISSUE THREAD

**Issue by zeneli** [rtosholdings/riptable#10]
Address new test failures given the smaller set of dependencies and across increased variety of platforms.

**Comment by jack-pappas** [comment]
The tests are all passing now as of 183ff0e, although I had to mark ``AccumTable.test_accum_table`` as being skipped -- it's doing something with ``numpy.random`` that causes the test to be flaky/inconsistent. That ought to be fixed so the data generation is deterministic, then we can re-enable the test.

**Comment by zeneli** [comment]
Now that the unit tests are in a passing state I'll begin enabling the tooling integration tests as well as the property based tests that use hypothesis.

**Comment by tdimitri** [comment]
Closing this - you can reopen as get hypothesis tests running well in Continuous Integration.
