### ISSUE TITLE
remove pandas constraint on conda spec

### ISSUE THREAD

**Issue by john-granieri** [rtosholdings/riptable#121]
there is a pandas constraint on the meta.yaml

    - pandas >=0.24,<1.1

This can be changed to pandas >=0.24, and remove the <1.1

Without the change, people have to install things as 'conda install --no-deps' and risk all the broken envs.

I tested riptable with numpy 1.20.1 and pandas 1.2.3, and it seems fine with regards to pandas.

Along with a notebook I have that exercises a bunch of pandas-to-riptide conversions and comparisons, I ran the riptable unit tests, and they all passed (there was some spewage for numpy deprecation warnings), except two, which aren't related to any pandas functionality.

```
!python riptable/tests/runall.py
... [ output elided ] ...
Failure: riptable.tests.test_accum2, riptable.tests.test_grouping

```

The env I ran with:

```
!conda list "numpy|pandas|riptide|riptable|numba"

# Name                    Version                   Build  Channel
numba                     0.53.0           py37h7dd73a4_0    defaults
numpy                     1.20.1           py37haa41c4c_0    defaults 
numpydoc                  1.1.0              pyhd3eb1b0_1    defaults
pandas                    1.2.3            py37ha9443f7_0    defaults
riptable                  1.0.43                   py37_0    defaults
riptide                   1.5.2                    py37_0    defaults
riptide_cpp               1.6.28          np120py37h2bc3f7f_0    defaults

...

Thanks

**Comment by jack-pappas** [comment]
Fixed by #128.
