### ISSUE TITLE
TimeSpan does not display day components of timespan

### ISSUE THREAD

**Issue by mlboulware** [rtosholdings/riptable#14]
In [11]: rt.TimeSpan(23,'h')

Out[11]: TimeSpan(['23:00:00.000000000'])

 

In [12]: rt.TimeSpan(24,'h')

Out[12]: TimeSpan(['00:00:00.000000000'])

 

In [13]: rt.TimeSpan(25,'h')

Out[13]: TimeSpan(['01:00:00.000000000'])

**Comment by tdimitri** [comment]
Fixing to this..
In [2]: TimeSpan(23,'h')
TimeSpan(['23:00:00.000000000'])

In [3]: TimeSpan(24,'h')
TimeSpan(['1d 00:00:00.000000000'])

In [4]: TimeSpan(25,'h')
TimeSpan(['1d 01:00:00.000000000'])

In [5]: TimeSpan(250,'h')
TimeSpan(['10d 10:00:00.000000000'])
