### ISSUE TITLE
ds[::-1] does nothing and no warning/error message

### ISSUE THREAD

**Issue by zhangyingmath** [rtosholdings/riptable#199]
```
ds = rt.Dataset({'f': [1,2]})

ds
#	f
0	1
1	2
```

## The following is wrong. There is also no warning or error message. 
```
ds[::-1]
#	f
0	1
1	2
```

The following is OK and it operates on a Dataset:
```
ds[::-1, :]
#	f
0	2
1	1
```

The following are OK as it operates on FastArray:
```
ds[::-1, 'f']
FastArray([2, 1])

ds['f'][::-1]
FastArray([2, 1])
```

**Comment by OrestZborowski-SIG** [comment]
Verified. rt.Dataset slicing by [] incorrectly slices by columns instead of by rows:
```
ds = rt.Dataset({'f': [1,2], 'g': [3,4]})
ds[::-1]
#   g   f
-   -   -
0   3   1
1   4   2
```
instead of:
```
   f  g
1  2  4
0  1  3
```

**Comment by OrestZborowski-SIG** [comment]
Actually, this is by design.
The rt.Dataset slices by column (as I mentioned above), which is by design.
It does not follow the same convention as pd.DataFrame for slicing by row.
