### ISSUE TITLE
In-place logical NOT function (rt.logical_noti)

### ISSUE THREAD

**Issue by jack-pappas** [rtosholdings/riptable#20]
I have some code which, in several places, builds up a logical (boolean) mask for the purposes of filtering a dataset; however, it does this in a way that it builds up the inverse mask then uses the logical_not operation (``~my_mask``) at the end because the logic is easier to understand that way (vs. rewriting the logic just to avoid the logical-NOT operation at the end).

In these cases, it would be useful to have an in-place version of logical-NOT which accepts a boolean mask and inverts it in-place to avoid the additional memory allocation that comes from using the normal ``~`` operator.

**Comment by tdimitri** [comment]
Can you do
np.logical_not(x, out=x)

see around line 1047 of rt_fastarray.py
https://github.com/rtosholdings/riptable/blob/ce25eebf0390ce98acedbbc1b942d31c4c98e498/riptable/rt_fastarray.py#L1045

**Comment by jack-pappas** [comment]
Yes, I think ``np.logical_not()`` with the ``out`` keyword should do what I need. Thanks!
