### ISSUE TITLE
BUG: rt.cut gives "Filtered" on an int column when bins contains np.inf

### ISSUE THREAD

**Issue by zhangyingmath** [rtosholdings/riptable#33]
rt.__version__
'1.0.19'

ds = rt.rt_dataset.Dataset({'f': [0, 1, 10, 100, 5]})
ds['g'] = ds['f'].astype(float)
ds

\#	f	g
0	0	0.00
1	1	1.00
2	10	10.00
3	100	100.00
4	5	5.00

ds.dtypes
{'f': dtype('int64'), 'g': dtype('float64')}

# This gives expected result, although note in the resulting categorical, the bins are represented with floats. This is compatible with the doc string of rt.cut: "bins : ndarray of floats" 
rt.cut(ds['f'], [-100, 2, 11, 50, 1000])
Categorical([-100.0->2.0, -100.0->2.0, 2.0->11.0, 50.0->1000.0, 2.0->11.0]) Length: 5
  FastArray([1, 1, 2, 4, 2], dtype=int8) Base Index: 1
  FastArray([b'-100.0->2.0', b'2.0->11.0', b'11.0->50.0', b'50.0->1000.0'], dtype='|S12') Unique count: 4

# this results in the same:
rt.cut(ds['f'], [-100.0, 2.0, 11.0, 50.0, 1000.0]) == rt.cut(ds['f'], [-100, 2, 11, 50, 1000])
FastArray([ True,  True,  True,  True,  True])

# However, if the bins have np.inf, then when applying on a int column will give wrong result:
# this appears to me like a bug:
rt.cut(ds['f'], [-np.inf, 2, 11, 50, np.inf])
Categorical([Filtered, Filtered, Filtered, Filtered, Filtered]) Length: 5
  FastArray([0, 0, 0, 0, 0], dtype=int8) Base Index: 1
  FastArray([b'-inf->2.0', b'2.0->11.0', b'11.0->50.0', b'50.0->inf'], dtype='|S10') Unique count: 4

# Of course, applying on a float column is OK even when the bin contains np.inf, 
rt.cut(ds['g'], [-np.inf, 2, 11, 50, np.inf])
Categorical([-inf->2.0, -inf->2.0, 2.0->11.0, 50.0->inf, 2.0->11.0]) Length: 5
  FastArray([1, 1, 2, 4, 2], dtype=int8) Base Index: 1
  FastArray([b'-inf->2.0', b'2.0->11.0', b'11.0->50.0', b'50.0->inf'], dtype='|S10') Unique count: 4

**Comment by tdimitri** [comment]
This was a bug and I am checking in a fix now.

**Comment by zhangyingmath** [comment]
Thanks!
