### ISSUE TITLE
When doing category.ema_normal with a filter, the filtered out values are treated as zero

### ISSUE THREAD

**Issue by tdimitri** [rtosholdings/riptable#37]
When doing category.ema_normal with a filter, the filtered out values are treated as zero.

```
r = np.arange(10, dtype=float) + 1000
tmp = rt.Dataset({'x': r,
                  'x_zero': r.copy(),
                  'fltr': rt.FA([True]*10)})
tmp.x_zero[5] = 0
tmp.fltr[5] = False

c = rt.Cat([0]*10)
t = r

tmp['ema_x'] = c.ema_normal(tmp['x'], time=t, decay_rate=1)
tmp['ema_x_zero'] = c.ema_normal(tmp['x_zero'], time=t, decay_rate=1)
tmp['ema_x_filtered'] = c.ema_normal(tmp['x'], time=t, filter=tmp.fltr, decay_rate=1)
print(tmp)
```

produces:
```
#          x     x_zero    fltr      ema_x   ema_x_zero   ema_x_filtered
-   --------   --------   -----   --------   ----------   --------------
0   1,000.00   1,000.00    True   1,000.00     1,000.00         1,000.00
1   1,001.00   1,001.00    True   1,000.63     1,000.63         1,000.63
2   1,002.00   1,002.00    True   1,001.50     1,001.50         1,001.50
3   1,003.00   1,003.00    True   1,002.45     1,002.45         1,002.45
4   1,004.00   1,004.00    True   1,003.43     1,003.43         1,003.43
5   1,005.00       0.00   False   1,004.42       369.14           369.14
6   1,006.00   1,006.00    True   1,005.42       771.71           771.71
7   1,007.00   1,007.00    True   1,006.42       920.44           920.44
8   1,008.00   1,008.00    True   1,007.42       975.79           975.79
9   1,009.00   1,009.00    True   1,008.42       996.78           996.78
```

ema_x_filtered should be close to ema_x, without the big drop at index 5. The same issue happens with ema_decay. I am not sure about ema_weighted as I get an error running it.

**Comment by MarcMassar** [comment]
Is this doing a fill forward of the ema over the filtered out values? 

When I looked at the cpp code, I had the impression that in effect it would fill-forward the values before doing the ema. That would be a little better; but just doing ffill on the ema is good enough.

**Comment by tdimitri** [comment]
Can you see the link below?  The code change is in riptide_cpp
[ema code change](https://github.com/rtosholdings/riptide_cpp/commit/5919c8c4c9002e72d21cd3a68e633b151c407239#diff-22a084712c30815d9f930e35755dc09324a823f141e63fa3b4838f1ff9c51a51
)

` pDest[i] = pLastEma[location];`

It is simply taking the last good output value, and putting it back in.  So 1003.43 repeats again.. but I think what you want is to take the last good input value and run it through the ema decay.

**Comment by MarcMassar** [comment]
Yes, that's it. From the test case above, I would expect the result to be:
```
x_ff = tmp.x.where(tmp.fltr)
x_ff.fill_forward(inplace=True)
tmp['ema_expected'] = c.ema_normal(x_ff, time=t, decay_rate=1)
```

The logic being that the best guess for the filtered out value is the last value (at least in finance where I don't want to look in the future, so fill_forward is the best we can/should do).

If I understand the code correctly, you would need to revert the changes and create a pLastValue array to remember the last seen value, and use that to initialize value if it is filtered out.

**Comment by tdimitri** [comment]
New checkin which acts like fill forward

```
#         x    x_zero    fltr     ema_x   ema_x_zero   ema_x_filtered
-   -------   -------   -----   -------   ----------   --------------
0   1000.00   1000.00    True   1000.00      1000.00          1000.00
1   1001.00   1001.00    True   1000.63      1000.63          1000.63
2   1002.00   1002.00    True   1001.50      1001.50          1001.50
3   1003.00   1003.00    True   1002.45      1002.45          1002.45
4   1004.00   1004.00    True   1003.43      1003.43          1003.43
5   1005.00      0.00   False   1004.42       369.14          1003.79
6   1006.00   1006.00    True   1005.42       771.71          1005.19
7   1007.00   1007.00    True   1006.42       920.44          1006.33
8   1008.00   1008.00    True   1007.42       975.79          1007.39
9   1009.00   1009.00    True   1008.42       996.78          1008.41

```
