### ISSUE TITLE
Installation issue from a fresh environment

### ISSUE THREAD

**Issue by tmcclintock** [rtosholdings/riptable#6]
`riptable` does not seem to install from source within a fresh environment.

Steps to reproduce (all of this was ran from the top level of the repo except otherwise stated):

1) Create an anaconda environment. As an example, here is a "developer's" environment file I created (`environment.yml`):
```yml
name: rtdev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - numpy
  - scipy
  - numba
  - python-dateutil
  - pandas
  - pre-commit
  - black
  - flake8
  - pytest
  - coverage
```

2) [Install and activate the environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file)
```bash
conda env create -f environment.yml
conda activate rtdev
```

3) Install `riptable`
```bash
python setup.py install
```

4) Attempt to import `riptable` from inside python (same result when running from the top of the repo or from other places):
```bash
python -c "import riptable"
```
which is met with the following error:
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tmcclintock/Github/riptable/riptable/__init__.py", line 10, in <module>
    from .rt_fastarray import FastArray, Threading, Recycle, Ledger
  File "/Users/tmcclintock/Github/riptable/riptable/rt_fastarray.py", line 9, in <module>
    import riptide_cpp as rc
ImportError: dlopen(/opt/anaconda3/envs/rtdev/lib/python3.8/site-packages/riptide_cpp-1.5-py3.8-macosx-10.9-x86_64.egg/riptide_cpp.cpython-38-darwin.so, 2): Library not loaded: @rpath/libzstd.1.dylib
  Referenced from: /opt/anaconda3/envs/rtdev/lib/python3.8/site-packages/riptide_cpp-1.5-py3.8-macosx-10.9-x86_64.egg/riptide_cpp.cpython-38-darwin.so
  Reason: image not found
```

Of note: running `$pip install riptable` again yields the following:
```bash
Requirement already satisfied: riptable in /opt/anaconda3/envs/rtdev/lib/python3.8/site-packages/riptable-1.0.3-py3.8.egg (1.0.3)
Requirement already satisfied: numpy in /opt/anaconda3/envs/rtdev/lib/python3.8/site-packages (from riptable) (1.19.1)
Requirement already satisfied: riptide_cpp in /opt/anaconda3/envs/rtdev/lib/python3.8/site-packages/riptide_cpp-1.5-py3.8-macosx-10.9-x86_64.egg (from riptable) (1.5)
Requirement already satisfied: ansi2html in /opt/anaconda3/envs/rtdev/lib/python3.8/site-packages/ansi2html-1.5.2-py3.8.egg (from riptable) (1.5.2)
Requirement already satisfied: numba in /opt/anaconda3/envs/rtdev/lib/python3.8/site-packages (from riptable) (0.51.1)
Requirement already satisfied: six in /opt/anaconda3/envs/rtdev/lib/python3.8/site-packages (from ansi2html->riptable) (1.15.0)
Requirement already satisfied: llvmlite<0.35,>=0.34.0.dev0 in /opt/anaconda3/envs/rtdev/lib/python3.8/site-packages (from numba->riptable) (0.34.0)
Requirement already satisfied: setuptools in /opt/anaconda3/envs/rtdev/lib/python3.8/site-packages (from numba->riptable) (49.6.0.post20200814)
```
which indicates that `riptide_cpp` is installed, but for whatever reason the `rpath/libzstd.1.dylib` image did not get put into the proper place in the path.

System details:
MacOS - 10.15.4
python - 3.8.5 (same issue with 3.7)

**Suggested solution**:
Somehow ensure that installer for `riptide_cpp` works correctly, but not entirely sure how to do this. Happy to raise this issue in that repo instead.

Note that I did not encounter this issue when installing `riptable` in linux machines.

**Comment by tmcclintock** [comment]
Workaround: I installed `zstd` before creating the environment with
```bash
brew install zstd
```
and performed all the steps above without issue.

My new suggested solution is to properly declare the `zstd` dependency. There must be an error in the [`CMakeLists.txt`](https://github.com/rtosholdings/riptable/blob/master/CMakeLists.txt) file, but since I do not know cmake I cannot be much help here.

**Comment by tdimitri** [comment]
Yes, this is related to setup.py in riptide_cpp for Mac.  It does not build zstd but rather links to it because when I try to build zstd I get an error that I need to work around.

**Comment by OrestZborowski-SIG** [comment]
we no longer support MacOS.
