### ISSUE TITLE
speedup record array to dataset (do in parallel)

### ISSUE THREAD

**Issue by tdimitri** [rtosholdings/riptable#65]

**Comment by jack-pappas** [comment]
Another way to think about this is as a fast, parallelized conversion between the AoS (array of structs) and SoA (struct of arrays) data layouts: a numpy ``recarray`` is AoS layout and a ``Dataset`` provides SoA layout.

https://en.wikipedia.org/wiki/AoS_and_SoA

**Comment by jack-pappas** [comment]
This was implemented in f23573c2.
