### ISSUE TITLE
`ema_decay` incorrect computation when used with categoricals (does not decay on filtered values)

### ISSUE THREAD

**Issue by kwu93** [rtosholdings/riptable#72]
For `ema_decay`, we want to decay the sum on filtered values. For example, if we are summing the occurrences of some event (that passes our filter), and we see a stream of events that do not meet our criteria, our logged value of the sum should be decayed by the relevant time. 

This seems to work correctly when called as `rt.FA.ema_decay` but does not when we use this within a categorical `cat.ema_decay()` etc. In the categorical case, the EMA series just fills forward with the previous known value.

I think a way to fix this is to basically replace filtered values with zero internally when doing the EMA, which I believe should be the default

# Example

This reproduces the bug. 
```
x = rt.ones(10)
t = np.arange(10)
f = rt.FA([True] * 5 + [False] * 4 + [True])
test = rt.Dataset({
    'x': np.tile(x, reps=2),
    't': np.tile(t, reps=2)
    'f': np.tile(f, reps=2),
    'c': rt.FA(["A"] * 10 + ["B"] * 10)
})

test['ema_default'] = test.cat('c').ema_decay(test.x, time=test.t, decay_rate=np.log(2), filter=test.f)
correct_ema = rt.FA.ema_decay(x, t, np.log(2), filter=f)
test['ema_correct'] = np.tile(correct_ema, reps=2)
```

**Comment by OrestZborowski-SIG** [comment]
This appears to be fixed by https://github.com/rtosholdings/riptide_cpp/pull/116
