### ISSUE TITLE
Feature request: readthedocs

### ISSUE THREAD

**Issue by tmcclintock** [rtosholdings/riptable#8]
`riptable` has a lot of docstrings, but no dedicated docs. Since it is open source, we should take advantage of an open source documentation platform like RTD.

I would be happy to do this, as I have created docs pages for other projects in SIG. Just let me know if we want a particular platform, or if RTD is fine.

**Comment by tdimitri** [comment]
Although missing a true index page, I did get it to build: https://riptable.readthedocs.io/en/latest/index.html

**Comment by OrestZborowski-SIG** [comment]
we are working on updating the docs with each release.
