### ISSUE TITLE
GroupBy.mean giving spurious results for float32

### ISSUE THREAD

**Issue by eoincondron** [rtosholdings/riptable#92]
I have found that Groupby.mean applied to arrays of float32 type with 2*15 elements or more gives spurious results. 
In the example below I apply the same GroupBy.mean to the same array 5 times, getting different results. 

![image](https://user-images.githubusercontent.com/9717992/104577701-b2616880-5651-11eb-9820-7c1aaae7f905.png)

**Comment by jack-pappas** [comment]
@eoincondron had an older version of _riptide_cpp_ installed that was affected by the bug fixed in rtosholdings/riptide_cpp#17 -- the latest versions of riptable / riptide_cpp don't have this bug.
